language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.2
    - 7.3
    - 7.4

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini; fi

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - make lint-php
    - make php-cs-fixer-dry
    - make phpunit
